### ISSUE TITLE
Full ESLint support

### ISSUE THREAD

**Issue by jasonkuhrt** [thoughtbot/hound-eslint#16]
Hi! Great to see ESLint support coming.

From what I understand via #14 ESLint extensions and therefore likely plugins, parsers, etc. are not supported. This blocks us from using `houndci`. Are there plans to support arbitrary ESLint configs in the near future? https://github.com/thoughtbot/hound-eslint/issues/14#issuecomment-172830048 suggests _no_. As an alternative is it possible (I realize this is might be a big ask) that you can bless [littleBits' standards](https://github.com/littlebits/code-standards-js) like [you did with AirBnB](https://github.com/thoughtbot/hound-eslint/pull/15)?

Thanks.

**Comment by teoljungberg** [comment]
Hi @jasonkuhrt ,

You are correct, we are not going to allow arbitrary plugins to be run. But we'll gladly add them case by case.

The config for littlebits is installed in afe4493, and is deployed.

Since you seem to be the maintainer of the project, could you make sure to keep the package up to date in Hound?

**Comment by jasonkuhrt** [comment]
> The config for littlebits is installed in afe4493, and is deployed.

Wow fantastic!

> Since you seem to be the maintainer of the project, could you make sure to keep the package up to date in Hound?

Yes or one of my colleagues such as @sch.

**Comment by teoljungberg** [comment]
Thank you both!

**Comment by jasonkuhrt** [comment]
@teoljungberg Hey

We're testing right now but not _sure_ its working.

Given:
```
❯ cat .hound.yml

ruby:
  config_file: .rubocop.yml
scss:
  config_file: .scss-lint.yml
javascript:
  config_file: .jshintrc
  ignore_file: .jshintignore
eslint:
  enabled: true
  config_file: client/.eslintrc
  ignore_file: .eslintignore
```
```
❯ cat .eslintignore

app/**/*.js
```
```
❯ cat client/.eslintrc

extends: littlebits
```

We see that now HoundCI _seems_ to be "reviewing changes" indefinitely (whereas before it would finish after seconds or maybe a minute).

<img width="818" alt="screen shot 2016-01-26 at 8 53 45 am" src="https://cloud.githubusercontent.com/assets/284476/12582322/5ef1d056-c40a-11e5-92b7-cfad67115db8.png">

Anything we're missing?

Additionally, two questions:

* is `enabled: true` required within `eslint:`
* is `ignore_file` required within `eslint:` since it just points to the standard ignore file `.eslintignore`. Won't `eslint` automatically pick this up?

Thanks
